u1 = User.create(username: 'carlos', password: 'password')
u2 = User.create(username: 'guest', password: 'password')
u3 = User.create(username: 'user3', password: 'password')
u4 = User.create(username: 'user4', password: 'password')
u5 = User.create(username: 'user5', password: 'password')
u6 = User.create(username: 'user6', password: 'password')
u7 = User.create(username: 'user7', password: 'password')
u8 = User.create(username: 'user8', password: 'password')
u9 = User.create(username: 'user9', password: 'password')

Group.create(title: 'Nearby')
Group.create(title: 'San Francisco')
Group.create(title: 'Oakland')
Group.create(title: 'Berkeley')
Group.create(title: 'San Jose')
Group.create(title: 'Atlanta')

Following.create(group_id: 1, follower_id: 1)
Following.create(group_id: 6, follower_id: 1)
Following.create(group_id: 1, follower_id: 2)

p1 = u2.posts.create(author_id: 2, group_id: 3, body:"While in the shower: 2% washing, 7% singing, 91% winning fake arguments.")
p2 = u1.posts.create(author_id: 1, group_id: 1, body:"It's been 'one of those days' for like, 3 years now.")
p3 = u3.posts.create(author_id: 3, group_id: 2, body:"You never run out of toothpaste, just determination.")
p4 = u4.posts.create(author_id: 4, group_id: 4, body:"College Magic: And for my next trick, I will learn 8 weeks of material in 3 hours!", handle:'Berkeley')
p5 = u5.posts.create(author_id: 5, group_id: 1, body:"I hate when I gain 10 pounds for a role and then I remember I'm not an actor.", handle:'Hollywood')
p6 = u6.posts.create(author_id: 6, group_id: 3, body:"Gym Thoughts: Treadmill minutes are 5x longer than real minutes.", handle:'workout')
p7 = u7.posts.create(author_id: 7, group_id: 1, body:"I hate when people use a thesaurus to spice up their language, it really urinates me off.")
p8 = u8.posts.create(author_id: 8, group_id: 1, body:"I have 2 closets. 1 for Narnia and 1 for Monsters Inc.", handle:'Rad')
p9 = u9.posts.create(author_id: 9, group_id: 6, body:"I had a dream that I overslept and missed my 8am. Sometimes dreams do come true.", handle:'Georgia State')
p10 = u1.posts.create(author_id: 1, group_id: 1, body:"I hate when someone posts a blab quoting a song...it reminds me of somebody that I use to know.")
p11 = u2.posts.create(author_id: 2, group_id: 3, body:"Sweatpants are the best cause you can wear them to sleep and then wear them to class and no one will ever know.")
p12 = u3.posts.create(author_id: 3, group_id: 1, body:"Does finishing laundry make anyone else feel like they have their life together for a split second?")
p13 = u4.posts.create(author_id: 4, group_id: 2, body:"Let's play a game called: How late can I wake up while still making it to class?")
p14 = u5.posts.create(author_id: 5, group_id: 2, body:"Hands are weird because one can function perfectly and the other can't hold a spoon.")
p15 = u6.posts.create(author_id: 6, group_id: 1, body:"Sorry professor, the first backpack has been zipped. There's no stopping us now.", handle:'YEEHAW!')
p16 = u7.posts.create(author_id: 7, group_id: 3, body:"I dig. You dig. We dig. She digs. He digs. They dig... It's not a beautiful poem but it's very deep.")
p17 = u8.posts.create(author_id: 8, group_id: 3, body:"We never really grow up. We only learn how to act in public.")
p18 = u9.posts.create(author_id: 9, group_id: 1, body:"When my girlfriend told me to stop acting like a flamingo, I had to put my foot down.")
p19 = u1.posts.create(author_id: 1, group_id: 1, body:"Professors making students buy the books that they wrote is the college equivalent of: Check my mixtape, fam.'", handle:'Prof skrillex')
p20 = u2.posts.create(author_id: 2, group_id: 3, body:"We can put a man on the moon but God forbid the vending machine take my slightly bent dollar.")
p21 = u3.posts.create(author_id: 3, group_id: 1, body:"Fun drinking game: Take a shot of water every couple hours to make sure you're healthy and hydrated.")
p22 = u4.posts.create(author_id: 4, group_id: 4, body:"The barista just served me coffee and called me 'my love.' Took me 4 months to call my girlfriend that...it only took you 2 minutes and $2.26.")
p23 = u5.posts.create(author_id: 5, group_id: 6, body:"How many frat boys does it take to change a light bulb?  None, they prefer natural light.", handle:'the south')
p24 = u6.posts.create(author_id: 6, group_id: 1, body:"When a girl says 'lol have fun' do not have fun. Abort mission. I repeat. Abort mission.")
p25 = u7.posts.create(author_id: 7, group_id: 3, body:"IF YOU CANT HANDLE ME AT MY FINALS WEEK, YOU DONT DESERVE ME AT MY SYLLABUS WEEK.", handle:'CAPS')
p26 = u8.posts.create(author_id: 8, group_id: 6, body:"Dobby has no more finals, dobby is a free elf.", handle:'Georgia Tech')
p27 = u9.posts.create(author_id: 9, group_id: 5, body:"We all have that one friend who talks about how worried they are for their final but they have a 98 in the class...", handle:'Calc101')
p28 = u1.posts.create(author_id: 1, group_id: 5, body:"Finals Week: Where everyone who's never been to the library shows up and the regulars don't even bother trying.")
p29 = u2.posts.create(author_id: 2, group_id: 4, body:"I'll start eating better once they put healthy foods in microwaveable cups that cost me 10 cents.", handle:'meal plan?')
p30 = u3.posts.create(author_id: 3, group_id: 4, body:"I am rapidly running out of tomorrows on which to begin studying.")
p31 = u4.posts.create(author_id: 4, group_id: 5, body:"Day 4 at the yard: Milkshake has melted and is beginning to spoil, still no sign of boys.")
p34 = u5.posts.create(author_id: 5, group_id: 1, body:"Christmas is so close I can almost smell the mistletoe I'm not going to be kissed under.")
p35 = u6.posts.create(author_id: 6, group_id: 5, body:"I don't usually brag about my finances, but my credit card company calls me almost every day to tell me my balance is outstanding.", handle:'baller')
p36 = u7.posts.create(author_id: 7, group_id: 4, body:"I wish my bank account refilled as fast as my laundry basket.")
p37 = u8.posts.create(author_id: 8, group_id: 2, body:"No cough syrup, you're not 'grape flavored.' Have you ever tasted a grape? You taste like the death and tears of small children, not grape.")
p38 = u9.posts.create(author_id: 9, group_id: 2, body:"January, February, March, April, May, June, July, August, September, Halloween, Thanksgiving, Christmas.")
p39 = u1.posts.create(author_id: 1, group_id: 3, body:"I need you to lower your standards so I can date you.")
p40 = u2.posts.create(author_id: 2, group_id: 2, body:"The number of alarms I set is inversely proportionate to the number of hours of sleep I expect to get.")
p41 = u3.posts.create(author_id: 3, group_id: 5, body:"Legend has it, if you graduate with a 4.0 you reincarnate as a campus squirrel.", handle:'squirrely')
p42 = u4.posts.create(author_id: 4, group_id: 4, body:"Life's not a fairytale. If you lose your shoe at midnight, you're drunk.", handle:'smh')
p45 = u5.posts.create(author_id: 5, group_id: 4, body:"What if it doesn't want to be called hot sauce? What if it wants to be called beautiful sauce?", handle:'Saucy')
p46 = u6.posts.create(author_id: 6, group_id: 2, body:"He's such a hipster he burns his lips on his coffee because he drinks it before it's cool.", handle:'coffee cool')
p47 = u7.posts.create(author_id: 7, group_id: 2, body:"I love asking little kids what they want to be when they grow up because I'm still looking for ideas.")
p48 = u8.posts.create(author_id: 8, group_id: 6, body:"It just occured to me that I haven't said pop in reference to soda in years. The south has changed me.")
p49 = u9.posts.create(author_id: 9, group_id: 2, body:"I like that in college I can just accept the guy chilling outside my door with sharpie all over his chest as a natural part of life.")
p50 = u1.posts.create(author_id: 1, group_id: 2, body:"I just saw a dog walking through campus holding his own leash. Like, I'm an independent dog. I don't need no human.", handle:'dog power')
p51 = u2.posts.create(author_id: 2, group_id: 5, body:"Long distance relationships are so hard. I'm right here and she's so far in the future.", handle:'life')
p52 = u3.posts.create(author_id: 3, group_id: 3, body:"What if I told you that leaving your dishes in the sink doesn't clean them?", handle:'roomates')
p53 = u4.posts.create(author_id: 4, group_id: 1, body:"I thought Ariana Grande was a font on Microsoft Word.", handle:'Livininabubble')
p54 = u5.posts.create(author_id: 5, group_id: 4, body:"Face-timed my grandparents...got a good view of both their ears.")
p55 = u6.posts.create(author_id: 6, group_id: 4, body:"Everytime I get a salad I get mad because I start eating it and remember that I don't like salad.")
p56 = u7.posts.create(author_id: 7, group_id: 4, body:"Keep cake moist by eating it in one setting.")
p57 = u8.posts.create(author_id: 8, group_id: 2, body:"I show affection for my pets by holding them against me and whispering I love you repeatedly as they struggle to escape from my arm.", handle:"The only one?")
p58 = u9.posts.create(author_id: 9, group_id: 1, body:"Spilled hot tea on my leg, call that T-Pain.", handle:'Tea ouch')
p59 = u1.posts.create(author_id: 1, group_id: 6, body:"Yoga pants are like a push up bra for butts.", handle:'Sudden clarity')

p2.replies.create(body: 'feel the burn', author_id: 1)
p2.replies.create(body: 'if something is burnig go see the doc', author_id: 2)
p2.replies.create(body: 'true story', author_id: 3)
p2.replies.create(body: 'bummer', author_id: 2)
p5.replies.create(body: 'i do that sometimes', author_id: 2)
p5.replies.create(body: 'now I know you are on Yeehaw', author_id: 3)
p7.replies.create(body: 'HAHAHAHA', author_id: 1)
p7.replies.create(body: 'I can relate', author_id: 3)
p8.replies.create(body: 'Also known as the last mile', author_id: 1)
p8.replies.create(body: 'like my interenet connection', author_id: 3)
p10.replies.create(body: 'Radiate positive vibes', author_id: 1)
p12.replies.create(body: 'feel the burn', author_id: 1)
p12.replies.create(body: 'if something is burnig go see the doc', author_id: 2)
p12.replies.create(body: 'true story', author_id: 3)
p12.replies.create(body: 'bummer', author_id: 2)
p15.replies.create(body: 'i do that sometimes', author_id: 2)
p15.replies.create(body: 'now I know you are on Yeehaw', author_id: 3)
p18.replies.create(body: 'HAHAHAHA', author_id: 1)
p18.replies.create(body: 'I can relate', author_id: 3)
p19.replies.create(body: 'Also known as the last mile', author_id: 1)
p19.replies.create(body: 'like my interenet connection', author_id: 3)
p21.replies.create(body: 'Radiate positive vibes', author_id: 1)
p21.replies.create(body: 'feel the burn', author_id: 1)
p21.replies.create(body: 'if something is burnig go see the doc', author_id: 2)
p21.replies.create(body: 'true story', author_id: 3)
p21.replies.create(body: 'bummer', author_id: 2)
p34.replies.create(body: 'i do that sometimes', author_id: 2)
p34.replies.create(body: 'now I know you are on Yeehaw', author_id: 3)
p24.replies.create(body: 'HAHAHAHA', author_id: 1)
p24.replies.create(body: 'I can relate', author_id: 3)
