u1 = User.create(username: 'Guest1', password: 'password')
u2 = User.create(username: 'Guest2', password: 'password')
u3 = User.create(username: 'Guest3', password: 'password')
u4 = User.create(username: 'Guest4', password: 'password')
u5 = User.create(username: 'Guest5', password: 'password')
u6 = User.create(username: 'Guest6', password: 'password')
u7 = User.create(username: 'Guest7', password: 'password')
u8 = User.create(username: 'Guest8', password: 'password')
u9 = User.create(username: 'Guest9', password: 'password')

Group.create(title: 'Nearby')
Group.create(title: 'San Francisco')
Group.create(title: 'Oakland')
Group.create(title: 'Berkeley')
Group.create(title: 'San Jose')
Group.create(title: 'Atlanta')

Following.create(group_id: 1, follower_id: 1)
Following.create(group_id: 1, follower_id: 2)
Following.create(group_id: 1, follower_id: 3)
Following.create(group_id: 1, follower_id: 4)
Following.create(group_id: 1, follower_id: 5)
Following.create(group_id: 1, follower_id: 6)
Following.create(group_id: 1, follower_id: 7)
Following.create(group_id: 1, follower_id: 8)
Following.create(group_id: 1, follower_id: 9)
Following.create(group_id: 6, follower_id: 1)
Following.create(group_id: 2, follower_id: 2)
Following.create(group_id: 3, follower_id: 3)
Following.create(group_id: 4, follower_id: 4)
Following.create(group_id: 5, follower_id: 5)
Following.create(group_id: 6, follower_id: 6)
Following.create(group_id: 2, follower_id: 7)
Following.create(group_id: 3, follower_id: 8)
Following.create(group_id: 4, follower_id: 9)

p2 = u1.posts.create(author_id: 1, group_id: 1, body:"It's been 'one of those days' for like, 3 years now.")
p3 = u3.posts.create(author_id: 3, group_id: 2, body:"You never run out of toothpaste, just determination.")
p4 = u4.posts.create(author_id: 4, group_id: 4, body:"College Magic: And for my next trick, I will learn 8 weeks of material in 3 hours!", handle:'Berkeley')
p5 = u5.posts.create(author_id: 5, group_id: 1, body:"I hate when I gain 10 pounds for a role and then I remember I'm not an actor.", handle:'Hollywood')
p6 = u6.posts.create(author_id: 6, group_id: 3, body:"Gym Thoughts: Treadmill minutes are 5x longer than real minutes.", handle:'workout')
p8 = u8.posts.create(author_id: 8, group_id: 1, body:"I have 2 closets. 1 for Narnia and 1 for Monsters Inc.", handle:'Rad')
p9 = u9.posts.create(author_id: 9, group_id: 6, body:"I had a dream that I overslept and missed my 8am. Sometimes dreams do come true.", handle:'Georgia State')
p10 = u1.posts.create(author_id: 1, group_id: 1, body:"I hate when someone posts quoting a song...it reminds me of somebody that I use to know.")
p11 = u2.posts.create(author_id: 2, group_id: 3, body:"Sweatpants are the best cause you can wear them to sleep and then wear them to class and no one will ever know.")
p12 = u3.posts.create(author_id: 3, group_id: 1, body:"Does finishing laundry make anyone else feel like they have their life together for a split second?")
p13 = u4.posts.create(author_id: 4, group_id: 2, body:"Let's play a game called: How late can I wake up while still making it to class?")
p14 = u5.posts.create(author_id: 5, group_id: 2, body:"Hands are weird because one can function perfectly and the other can't hold a spoon.")
p18 = u9.posts.create(author_id: 9, group_id: 1, body:"When my girlfriend told me to stop acting like a flamingo, I had to put my foot down.")
p19 = u1.posts.create(author_id: 1, group_id: 1, body:"Professors making students buy the books that they wrote is the college equivalent of: Check my mixtape, fam.'")
p20 = u2.posts.create(author_id: 2, group_id: 3, body:"We can put a man on the moon but God forbid the vending machine take my slightly bent dollar.")
p21 = u3.posts.create(author_id: 3, group_id: 1, body:"Fun drinking game: Take a shot of water every couple hours to make sure you're healthy and hydrated.")
p22 = u4.posts.create(author_id: 4, group_id: 4, body:"The barista just served me coffee and called me 'my love.' Took me 4 months to call my girlfriend that...it only took you 2 minutes and $2.26.")
p24 = u6.posts.create(author_id: 6, group_id: 1, body:"When a girl says 'lol have fun' do not have fun. Abort mission. I repeat. Abort mission.")
p25 = u7.posts.create(author_id: 7, group_id: 3, body:"My greatest achievement in my 4 years at college is not ever losing my ID card.", handle:'Small victories')
p26 = u8.posts.create(author_id: 8, group_id: 6, body:"Dobby has no more finals, dobby is a free elf.", handle:'Georgia Tech')
p27 = u9.posts.create(author_id: 9, group_id: 5, body:"We all have that one friend who talks about how worried they are for their final but they have a 98 in the class...", handle:'Calc101')
p28 = u1.posts.create(author_id: 1, group_id: 5, body:"Finals Week: Where everyone who's never been to the library shows up and the regulars don't even bother trying.")
p29 = u2.posts.create(author_id: 2, group_id: 4, body:"I'll start eating better once they put healthy foods in microwaveable cups that cost me 10 cents.", handle:'meal plan?')
p30 = u3.posts.create(author_id: 3, group_id: 4, body:"I am rapidly running out of tomorrows on which to begin studying.")
p31 = u4.posts.create(author_id: 4, group_id: 5, body:"Day 4 at the yard: Milkshake has melted and is beginning to spoil, still no sign of boys.")
p35 = u6.posts.create(author_id: 6, group_id: 5, body:"I don't usually brag about my finances, but my credit card company calls me almost every day to tell me my balance is outstanding.", handle:'baller')
p36 = u7.posts.create(author_id: 7, group_id: 4, body:"I wish my bank account refilled as fast as my laundry basket.")
p37 = u8.posts.create(author_id: 8, group_id: 2, body:"No cough syrup, you're not 'grape flavored.' Have you ever tasted a grape? You taste like the death and tears of small children, not grape.")
p38 = u9.posts.create(author_id: 9, group_id: 2, body:"January, February, March, April, May, June, July, August, September, Halloween, Thanksgiving, Christmas.")
p40 = u2.posts.create(author_id: 2, group_id: 2, body:"The number of alarms I set is inversely proportionate to the number of hours of sleep I expect to get.")
p41 = u3.posts.create(author_id: 3, group_id: 5, body:"Legend has it, if you graduate with a 4.0 you reincarnate as a campus squirrel.", handle:'squirrely')
p45 = u5.posts.create(author_id: 5, group_id: 4, body:"What if it doesn't want to be called hot sauce? What if it wants to be called beautiful sauce?", handle:'Saucy')
p46 = u6.posts.create(author_id: 6, group_id: 2, body:"He's such a hipster he burns his lips on his coffee because he drinks it before it's cool.", handle:'coffee cool')
p47 = u7.posts.create(author_id: 7, group_id: 2, body:"I love asking little kids what they want to be when they grow up because I'm still looking for ideas.")
p48 = u8.posts.create(author_id: 8, group_id: 6, body:"It just occured to me that I haven't said pop in reference to soda in years. The south has changed me.")
p50 = u1.posts.create(author_id: 1, group_id: 2, body:"I just saw a dog walking through campus holding his own leash. Like, I'm an independent dog. I don't need no human.", handle:'dog power')
p51 = u2.posts.create(author_id: 2, group_id: 5, body:"Long distance relationships are so hard. I'm right here and she's so far in the future.", handle:'life')
p15 = u6.posts.create(author_id: 6, group_id: 1, body:"Sorry professor, the first backpack has been zipped. There's no stopping us now.", handle:'YEEHAW!')
p52 = u3.posts.create(author_id: 3, group_id: 3, body:"What if I told you that leaving your dishes in the sink doesn't clean them?", handle:'roomates')
p53 = u4.posts.create(author_id: 4, group_id: 1, body:"I thought Ariana Grande was a font on Microsoft Word.", handle:'Livininabubble')
p54 = u5.posts.create(author_id: 5, group_id: 4, body:"Face-timed my grandparents...got a good view of both their ears.")
p55 = u6.posts.create(author_id: 6, group_id: 4, body:"Everytime I get a salad I get mad because I start eating it and remember that I don't like salad.")
p56 = u7.posts.create(author_id: 7, group_id: 4, body:"Keep cake moist by eating it in one setting.")
p57 = u8.posts.create(author_id: 8, group_id: 2, body:"I show affection for my pets by holding them against me and whispering I love you repeatedly as they struggle to escape from my arm.", handle:"The only one?")
p58 = u9.posts.create(author_id: 9, group_id: 5, body:"Spilled hot tea on my leg, call that T-Pain.", handle:'Tea ouch')
p59 = u1.posts.create(author_id: 1, group_id: 6, body:"Can I ask you a million questions?", handle:'kids')
p60 = u2.posts.create(author_id: 2, group_id: 6, body:"Apparently I pack an apple in my 5 year old's lunch so it can get out of the house for a few hours.", handle:'kids')
p61 = u3.posts.create(author_id: 3, group_id: 2, body:"Stood in the bathroom for 2 minutes looking for the microwave. That's how my life is right about now.")
p62 = u4.posts.create(author_id: 4, group_id: 3, body:"There's a kid in my class who did the hunger games whistle and salute while the exams were being passed out.")
p63 = u5.posts.create(author_id: 5, group_id: 1, body:"Whenever I'm lonely, I remind myself that I'm a part of the worlds largest 4G LTE Network.")

p2.replies.create(body: 'feel the burn', author_id: 1)
p2.replies.create(body: 'if something is burnig go see the doc', author_id: 2)
p2.replies.create(body: 'true story', author_id: 3)
p2.replies.create(body: 'bummer', author_id: 2)
p5.replies.create(body: 'i do that sometimes', author_id: 4)
p5.replies.create(body: 'now I know you are on Yeehaw', author_id: 5)
p8.replies.create(body: 'Also known as the last mile', author_id: 6)
p8.replies.create(body: 'like my interenet connection', author_id: 7)
p10.replies.create(body: 'Radiate positive vibes', author_id: 8)
p12.replies.create(body: 'feel the burn', author_id: 9)
p12.replies.create(body: 'if something is burnig go see the doc', author_id: 2)
p12.replies.create(body: 'true story', author_id: 3)
p12.replies.create(body: 'bummer', author_id: 2)
p15.replies.create(body: 'i do that sometimes', author_id: 4)
p15.replies.create(body: 'now I know you are on Yeehaw', author_id: 5)
p18.replies.create(body: 'HAHAHAHA', author_id: 6)
p18.replies.create(body: 'I can relate', author_id: 7)
p19.replies.create(body: 'Also known as the last mile', author_id: 8)
p19.replies.create(body: 'like my interenet connection', author_id: 9)
p21.replies.create(body: 'Radiate positive vibes', author_id: 3)
p21.replies.create(body: 'feel the burn', author_id: 5)
p21.replies.create(body: 'if something is burnig go see the doc', author_id: 6)
p21.replies.create(body: 'true story', author_id: 8)
p21.replies.create(body: 'bummer', author_id: 2)
p63.replies.create(body: 'Can you hear me now?', author_id: 1)
